function resultado1(){
	document.getElementById("formulario1").style.display="inline-block";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado2(){
	document.getElementById("formulario2").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado3(){
	document.getElementById("formulario3").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado4(){
	document.getElementById("formulario4").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado5(){
	document.getElementById("formulario5").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado6(){
	document.getElementById("formulario6").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado7(){
	document.getElementById("formulario7").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado8(){
	document.getElementById("formulario8").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario9").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
function resultado9(){
	document.getElementById("formulario9").style.display="inline-block";
	document.getElementById("formulario1").style.display="none";
	document.getElementById("formulario2").style.display="none";
	document.getElementById("formulario3").style.display="none";
	document.getElementById("formulario4").style.display="none";
	document.getElementById("formulario5").style.display="none";
	document.getElementById("formulario6").style.display="none";
	document.getElementById("formulario7").style.display="none";
	document.getElementById("formulario8").style.display="none";
	document.getElementById("fotoCole").style.display="none";
}
